export enum PlayableContentImportParserErrorCode {
  EMPTY_FILE = 'PLAYABLE_CONTENT_IMPORT_EMPTY_FILE',
  INVALID_FILE = 'PLAYABLE_CONTENT_IMPORT_INVALID_FILE',
  UNSUPPORTED_FORMAT = 'PLAYABLE_CONTENT_IMPORT_UNSUPPORTED_FORMAT',
}
