apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "default.fullname" . }}
  labels:
    {{- include "default.labels" . | nindent 4 }}
data:
  VITE_API_URL: {{ .Values.config.apiUrl | quote }}
