{{- if or .Values.config.apiUrl .Values.config.feedbackUrl }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pleey.frontend.fullname" . }}
  labels:
    {{- include "pleey.frontend.labels" . | nindent 4 }}
data:
  {{- if .Values.config.apiUrl }}
  VITE_API_URL: {{ .Values.config.apiUrl | quote }}
  {{- end }}
  {{- if .Values.config.feedbackUrl }}
  VITE_FEEDBACK_URL: {{ .Values.config.feedbackUrl | quote }}
  {{- end }}
{{- end }}
