/**
 * Game Error Codes
 * Used to identify specific game-related errors
 */
export enum GameErrorCode {
  GAME_NOT_FOUND = 'GAME_NOT_FOUND',
  NO_QUESTIONS_AVAILABLE = 'NO_QUESTIONS_AVAILABLE',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  CAN_ONLY_PAUSE_ACTIVE_GAME = 'CAN_ONLY_PAUSE_ACTIVE_GAME',
  CAN_ONLY_RESUME_PAUSED_GAME = 'CAN_ONLY_RESUME_PAUSED_GAME',
  UNAUTHORIZED_SESSION_CONTROL = 'UNAUTHORIZED_SESSION_CONTROL',
  QUIZ_NOT_FOUND = 'QUIZ_NOT_FOUND',
  ACTIVE_SESSION_EXISTS = 'ACTIVE_SESSION_EXISTS',
}
