/**
 * Project Error Codes
 * Used for consistent error handling across the project domain
 */
export enum ProjectErrorCode {
  CANNOT_DELETE_LAST_PROJECT = 'CANNOT_DELETE_LAST_PROJECT',
  PROJECT_MIGRATION_TARGET_INVALID = 'PROJECT_MIGRATION_TARGET_INVALID',
  PROJECT_MIGRATION_TARGET_NOT_FOUND = 'PROJECT_MIGRATION_TARGET_NOT_FOUND',
  PROJECT_MIGRATION_TARGET_REQUIRED = 'PROJECT_MIGRATION_TARGET_REQUIRED',
  PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND',
}
