/**
 * Quiz Error Codes
 * Used to identify specific quiz-related errors
 */
export enum QuizErrorCode {
  QUIZ_NOT_FOUND = 'QUIZ_NOT_FOUND',
  QUESTION_NOT_FOUND = 'QUESTION_NOT_FOUND',
  QUIZ_HAS_ACTIVE_SESSION = 'QUIZ_HAS_ACTIVE_SESSION',
  INVALID_CORRECT_ANSWER = 'INVALID_CORRECT_ANSWER',
  CORRECT_ANSWER_OPTION_EMPTY = 'CORRECT_ANSWER_OPTION_EMPTY',
}
