export enum QuizErrorCode {
  QUIZ_NOT_FOUND = 'QUIZ_NOT_FOUND',
  QUESTION_NOT_FOUND = 'QUESTION_NOT_FOUND',
  QUIZ_HAS_ACTIVE_PARTY = 'QUIZ_HAS_ACTIVE_PARTY',
  INVALID_CORRECT_ANSWER = 'INVALID_CORRECT_ANSWER',
  CORRECT_ANSWER_OPTION_EMPTY = 'CORRECT_ANSWER_OPTION_EMPTY',
  QUIZ_IMPORT_INVALID_FILE = 'QUIZ_IMPORT_INVALID_FILE',
  QUIZ_IMPORT_UNSUPPORTED_FORMAT = 'QUIZ_IMPORT_UNSUPPORTED_FORMAT',
  QUIZ_IMPORT_EMPTY_FILE = 'QUIZ_IMPORT_EMPTY_FILE',
}
