apiVersion: v2
name: frontend
description: Pleey frontend service subchart.
type: application
version: 0.2.0
appVersion: "0.2.0"
home: https://github.com/cloud-native-aixmarseille/pleey
sources:
  - https://github.com/cloud-native-aixmarseille/pleey
keywords:
  - pleey
  - frontend
  - react
  - nginx
maintainers:
  - name: Pleey Maintainers
    url: https://github.com/cloud-native-aixmarseille/pleey
icon: https://raw.githubusercontent.com/cloud-native-aixmarseille/pleey/main/application/frontend/public/favicon/favicon.svg
