apiVersion: v1
kind: Secret
metadata:
  name: {{ include "default.fullname" . }}
  annotations:
    {{- include "default.annotations" . | nindent 4 }}
  labels:
    {{- include "default.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.config.secrets.jwtSecret | default (randAlphaNum 32) | b64enc }}
  DATABASE_URL: {{ include "default.databaseUrl" . | b64enc }}
