{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pleey.fullname" . }}-backend
  namespace: {{ include "pleey.namespace" . | quote }}
  labels:
    {{- include "pleey.backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.backend.secrets.jwtSecret | quote }}
  database-url: {{ include "pleey.databaseUrl" . | quote }}
{{- end }}
