/**
 * Organization Error Codes
 * Used for consistent error handling across the organization domain
 */
export enum OrganizationErrorCode {
  ORGANIZATION_NOT_FOUND = 'ORGANIZATION_NOT_FOUND',
  ORGANIZATION_NAME_ALREADY_EXISTS = 'ORGANIZATION_NAME_ALREADY_EXISTS',
  MEMBER_NOT_FOUND = 'MEMBER_NOT_FOUND',
  MEMBER_ALREADY_EXISTS = 'MEMBER_ALREADY_EXISTS',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  CANNOT_REMOVE_LAST_OWNER = 'CANNOT_REMOVE_LAST_OWNER',
  NOT_A_MEMBER = 'NOT_A_MEMBER',
}
