query WorkspaceProjectsByOrganization($input: ListOrganizationProjectsInput!) {
  organizationProjects(input: $input) {
    items {
      id
      name
      description
      organizationId
      createdAt
      defaultPartySettings {
        allowJoiningAfterStart
        allowOptionChangeAfterVoting
        randomizeOptionOrder
        randomizeStageOrder
      }
    }
    totalCount
    overallCount
    page
    pageSize
    totalPages
  }
}

mutation CreateProject($organizationId: ID!, $input: CreateProjectInput!) {
  createProject(organizationId: $organizationId, input: $input) {
    id
    name
    description
    organizationId
    createdAt
    defaultPartySettings {
      allowJoiningAfterStart
      allowOptionChangeAfterVoting
      randomizeOptionOrder
      randomizeStageOrder
    }
  }
}

mutation UpdateProject($projectId: ID!, $input: UpdateProjectInput!) {
  updateProject(projectId: $projectId, input: $input) {
    id
    name
    description
    organizationId
    createdAt
    defaultPartySettings {
      allowJoiningAfterStart
      allowOptionChangeAfterVoting
      randomizeOptionOrder
      randomizeStageOrder
    }
  }
}

mutation DeleteProject($projectId: ID!, $migrationProjectId: ID) {
  deleteProject(projectId: $projectId, migrationProjectId: $migrationProjectId)
}
