{{- if and (eq .Values.gateway.provider "ingress") .Values.frontend.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pleey.fullname" . }}
  labels:
    {{- include "pleey.labels" . | nindent 4 }}
  {{- with .Values.gateway.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.gateway.ingress.className }}
  ingressClassName: {{ .Values.gateway.ingress.className | quote }}
  {{- end }}
  {{- with .Values.gateway.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.gateway.ingress.host | quote }}
      http:
        paths:
          {{- if .Values.backend.enabled }}
          - path: {{ .Values.gateway.ingress.graphqlPath | quote }}
            pathType: {{ .Values.gateway.ingress.pathType }}
            backend:
              service:
                name: {{ include "pleey.backend.fullname" . }}
                port:
                  number: {{ include "pleey.backend.servicePort" . }}
          - path: {{ .Values.gateway.ingress.apiPath | quote }}
            pathType: {{ .Values.gateway.ingress.pathType }}
            backend:
              service:
                name: {{ include "pleey.backend.fullname" . }}
                port:
                  number: {{ include "pleey.backend.servicePort" . }}
          - path: {{ .Values.gateway.ingress.socketPath | quote }}
            pathType: {{ .Values.gateway.ingress.pathType }}
            backend:
              service:
                name: {{ include "pleey.backend.fullname" . }}
                port:
                  number: {{ include "pleey.backend.servicePort" . }}
          {{- end }}
          - path: {{ .Values.gateway.ingress.frontendPath | quote }}
            pathType: {{ .Values.gateway.ingress.pathType }}
            backend:
              service:
                name: {{ include "pleey.frontend.fullname" . }}
                port:
                  number: {{ include "pleey.frontend.servicePort" . }}
{{- end }}