{{- if .Values.podDisruptionBudget.enabled }}
{{- if .Values.backend.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "pleey.backend.fullname" . }}
  labels:
    {{- include "pleey.backend.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "pleey.backend.selectorLabels" . | nindent 6 }}
---
{{- end }}
{{- if .Values.frontend.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "pleey.frontend.fullname" . }}
  labels:
    {{- include "pleey.frontend.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "pleey.frontend.selectorLabels" . | nindent 6 }}
{{- end }}
{{- end }}