{{- if .Values.valkey.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pleey.valkey.fullname" . }}
  namespace: {{ include "pleey.namespace" . | quote }}
  labels:
    {{- include "pleey.valkey.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pleey.valkey.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pleey.valkey.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.valkey.podSecurityContext | nindent 8 }}
      containers:
        - name: valkey
          {{- $valkeyImage := .Values.valkey.image.repository -}}
          {{- if .Values.valkey.image.digest }}
          image: {{ printf "%s@%s" $valkeyImage .Values.valkey.image.digest | quote }}
          {{- else }}
          image: {{ printf "%s:%s" $valkeyImage .Values.valkey.image.tag | quote }}
          {{- end }}
          imagePullPolicy: {{ .Values.valkey.image.pullPolicy | default "IfNotPresent" }}
          securityContext:
            {{- toYaml .Values.valkey.securityContext | nindent 12 }}
          args:
            - "--save"
            - ""
            - "--appendonly"
            - "no"
          ports:
            - name: redis
              containerPort: {{ .Values.valkey.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.valkey.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.valkey.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.valkey.readinessProbe | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: data
          emptyDir: {}
        - name: tmp
          emptyDir: {}
{{- end }}
