{{- if .Values.valkey.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pleey.valkey.fullname" . }}
  namespace: {{ include "pleey.namespace" . | quote }}
  labels:
    {{- include "pleey.valkey.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: {{ .Values.valkey.service.port }}
      targetPort: redis
      protocol: TCP
  selector:
    {{- include "pleey.valkey.selectorLabels" . | nindent 4 }}
{{- end }}
