export enum PresentationContextErrorCode {
  AUTH_PROVIDER_REQUIRED = 'AUTH_PROVIDER_REQUIRED',
  GAME_LOBBY_PROVIDER_REQUIRED = 'GAME_LOBBY_PROVIDER_REQUIRED',
  GAME_PLAYING_PROVIDER_REQUIRED = 'GAME_PLAYING_PROVIDER_REQUIRED',
  GAME_PROVIDER_REQUIRED = 'GAME_PROVIDER_REQUIRED',
  GAME_SESSION_ROUTE_PROVIDER_REQUIRED = 'GAME_SESSION_ROUTE_PROVIDER_REQUIRED',
  PRESENTATION_FORM_PROVIDER_REQUIRED = 'PRESENTATION_FORM_PROVIDER_REQUIRED',
  PRESENTATION_RUNTIME_DEPENDENCY_PROVIDER_REQUIRED = 'PRESENTATION_RUNTIME_DEPENDENCY_PROVIDER_REQUIRED',
  PRESENTATION_ROUTING_PROVIDER_REQUIRED = 'PRESENTATION_ROUTING_PROVIDER_REQUIRED',
  PRESENTATION_TRANSLATION_PROVIDER_REQUIRED = 'PRESENTATION_TRANSLATION_PROVIDER_REQUIRED',
  PRESENTATION_UI_PROVIDER_REQUIRED = 'PRESENTATION_UI_PROVIDER_REQUIRED',
}
