export enum PresentationContextErrorCode {
  AUTH_PROVIDER_REQUIRED = 'AUTH_PROVIDER_REQUIRED',
  PARTY_PROVIDER_REQUIRED = 'PARTY_PROVIDER_REQUIRED',
  PRESENTATION_FORM_PROVIDER_REQUIRED = 'PRESENTATION_FORM_PROVIDER_REQUIRED',
  PRESENTATION_RUNTIME_DEPENDENCY_PROVIDER_REQUIRED = 'PRESENTATION_RUNTIME_DEPENDENCY_PROVIDER_REQUIRED',
  PRESENTATION_ROUTING_PROVIDER_REQUIRED = 'PRESENTATION_ROUTING_PROVIDER_REQUIRED',
  PRESENTATION_TOAST_PROVIDER_REQUIRED = 'PRESENTATION_TOAST_PROVIDER_REQUIRED',
  PRESENTATION_TRANSLATION_PROVIDER_REQUIRED = 'PRESENTATION_TRANSLATION_PROVIDER_REQUIRED',
  PRESENTATION_UI_PROVIDER_REQUIRED = 'PRESENTATION_UI_PROVIDER_REQUIRED',
}
