/**
 * Game Error Codes
 * Used to identify specific game-related errors
 */
export enum GameErrorCode {
  GAME_NOT_FOUND = 'GAME_NOT_FOUND',
  GAME_SESSION_NOT_FOUND = 'GAME_SESSION_NOT_FOUND',
  NO_STAGES_AVAILABLE = 'NO_STAGES_AVAILABLE',
  NO_CURRENT_STAGE_TO_RESUME = 'NO_CURRENT_STAGE_TO_RESUME',
  INVALID_REVEAL_DELAY = 'INVALID_REVEAL_DELAY',
  PLAYER_IDENTITY_REQUIRED = 'PLAYER_IDENTITY_REQUIRED',
  PLAYER_SCORE_IDENTITY_INVALID = 'PLAYER_SCORE_IDENTITY_INVALID',
  INVALID_PIN = 'INVALID_PIN',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  CAN_ONLY_PAUSE_ACTIVE_GAME = 'CAN_ONLY_PAUSE_ACTIVE_GAME',
  CAN_ONLY_RESUME_PAUSED_GAME = 'CAN_ONLY_RESUME_PAUSED_GAME',
  CAN_ONLY_START_WAITING_GAME = 'CAN_ONLY_START_WAITING_GAME',
  CAN_ONLY_MOVE_TO_NEXT_STAGE_ACTIVE_GAME = 'CAN_ONLY_MOVE_TO_NEXT_STAGE_ACTIVE_GAME',
  UNAUTHORIZED_SESSION_CONTROL = 'UNAUTHORIZED_SESSION_CONTROL',
  ACTIVE_SESSION_EXISTS = 'ACTIVE_SESSION_EXISTS',
  GAME_ALREADY_HAS_ACTIVE_SESSION = 'GAME_ALREADY_HAS_ACTIVE_SESSION',
  ALREADY_ACTED = 'ALREADY_ACTED',
  GAME_SESSION_ENDED = 'GAME_SESSION_ENDED',
  GAME_TYPE_NOT_SUPPORTED = 'GAME_TYPE_NOT_SUPPORTED',
}
