/**
 * Game Error Codes
 * Used to identify specific game-related errors
 */
export enum GameErrorCode {
  GAME_NOT_FOUND = 'GAME_NOT_FOUND',
  NO_QUESTIONS_AVAILABLE = 'NO_QUESTIONS_AVAILABLE',
  NO_CURRENT_QUESTION_TO_RESUME = 'NO_CURRENT_QUESTION_TO_RESUME',
  INVALID_REVEAL_DELAY = 'INVALID_REVEAL_DELAY',
  PLAYER_IDENTITY_REQUIRED = 'PLAYER_IDENTITY_REQUIRED',
  PLAYER_SCORE_IDENTITY_INVALID = 'PLAYER_SCORE_IDENTITY_INVALID',
  INVALID_PIN = 'INVALID_PIN',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  CAN_ONLY_PAUSE_ACTIVE_GAME = 'CAN_ONLY_PAUSE_ACTIVE_GAME',
  CAN_ONLY_RESUME_PAUSED_GAME = 'CAN_ONLY_RESUME_PAUSED_GAME',
  CAN_ONLY_START_WAITING_GAME = 'CAN_ONLY_START_WAITING_GAME',
  CAN_ONLY_MOVE_TO_NEXT_QUESTION_ACTIVE_GAME = 'CAN_ONLY_MOVE_TO_NEXT_QUESTION_ACTIVE_GAME',
  UNAUTHORIZED_SESSION_CONTROL = 'UNAUTHORIZED_SESSION_CONTROL',
  QUIZ_NOT_FOUND = 'QUIZ_NOT_FOUND',
  ACTIVE_SESSION_EXISTS = 'ACTIVE_SESSION_EXISTS',
  QUIZ_SESSION_ALREADY_ACTIVE = 'QUIZ_SESSION_ALREADY_ACTIVE',
  ALREADY_ANSWERED = 'ALREADY_ANSWERED',
  GAME_SESSION_ENDED = 'GAME_SESSION_ENDED',
}
