query WorkspaceOrganizations($input: ListOrganizationsInput) {
  myOrganizations(input: $input) {
    items {
      id
      name
      description
      createdAt
      updatedAt
      defaultPartySettings {
        allowJoiningAfterStart
        allowOptionChangeAfterVoting
        randomizeOptionOrder
        randomizeStageOrder
      }
      role
    }
    totalCount
    overallCount
    page
    pageSize
    totalPages
  }
}

mutation UpdateOrganization($organizationId: ID!, $input: UpdateOrganizationInput!) {
  updateOrganization(organizationId: $organizationId, input: $input) {
    id
    name
    description
    createdAt
    updatedAt
    defaultPartySettings {
      allowJoiningAfterStart
      allowOptionChangeAfterVoting
      randomizeOptionOrder
      randomizeStageOrder
    }
    role
  }
}
