query QuizManagement($quizId: ID!, $input: PaginationInput!) {
  quiz(quizId: $quizId) {
    quizId
    gameId
    title
    description
    createdAt
    questionCount
  }
  quizQuestions(quizId: $quizId, input: $input) {
    ...QuizManagementItemsPage
  }
}

mutation UpdateQuizManagement($quizId: ID!, $input: UpdateQuizInput!) {
  updateQuiz(quizId: $quizId, input: $input) {
    quizId
  }
}

mutation CreateQuizManagement($input: CreateQuizInput!) {
  createQuiz(input: $input) {
    quizId
  }
}

mutation CreateQuizFromImportManagement($input: CreateQuizFromImportInput!) {
  createQuizFromImport(input: $input) {
    quizId
    questionCount
  }
}

mutation DeleteQuizManagement($quizId: ID!) {
  deleteQuiz(quizId: $quizId)
}

mutation CreateQuizQuestionManagement($input: CreateQuizQuestionInput!) {
  createQuizQuestion(input: $input) {
    id
    quizId
    position
    questionText
    type
    timeLimit
    points
    answers {
      id
      text
      position
      isCorrect
    }
  }
}

mutation UpdateQuizQuestionManagement($questionId: ID!, $input: UpdateQuizQuestionInput!) {
  updateQuizQuestion(questionId: $questionId, input: $input) {
    id
    quizId
    position
    questionText
    type
    timeLimit
    points
    answers {
      id
      text
      position
      isCorrect
    }
  }
}

mutation DeleteQuizQuestionManagement($questionId: ID!) {
  deleteQuizQuestion(questionId: $questionId)
}

query QuizManagementItems($quizId: ID!, $input: PaginationInput!) {
  quizQuestions(quizId: $quizId, input: $input) {
    ...QuizManagementItemsPage
  }
}

fragment QuizManagementItemsPage on QuizQuestionListType {
  items {
    id
    quizId
    position
    questionText
    type
    timeLimit
    points
    answers {
      id
      text
      position
      isCorrect
    }
  }
  totalCount
  overallCount
  page
  pageSize
  totalPages
}
