backend:
  image:
    tag: main
  ingress:
    enabled: true
    className: traefik-1768864371
    annotations: {}
    hosts:
      - host: pleey.k8s.orb.local
        paths:
          - path: /api
            pathType: ImplementationSpecific
          - path: /socket.io
            pathType: ImplementationSpecific
    tls: []
      # - secretName: chart-example-tls
      #   hosts:
      #     - chart-example.local

frontend:
  config:
    apiUrl: http://pleey.k8s.orb.local
  image:
    tag: main
  ingress:
    enabled: true
    className: traefik-1768864371
    annotations: {}
    hosts:
      - host: pleey.k8s.orb.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
      # - secretName: chart-example-tls
      #   hosts:
      #     - chart-example.local
