---
backend:
  image:
    tag: main
    digest: ""
frontend:
  image:
    tag: main
    digest: ""
  config:
    apiUrl: http://pleey.k8s.orb.local
gateway:
  ingress:
    className: traefik-1768864371
    host: pleey.k8s.orb.local
