{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quiz-app.fullname" . }}-backend
  labels:
    {{- include "quiz-app.backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.backend.secrets.jwtSecret | quote }}
  database-url: {{ include "quiz-app.databaseUrl" . | quote }}
{{- end }}
