/**
 * Authentication Error Codes
 * Used to identify specific authentication errors
 */
export enum AuthErrorCode {
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  PASSWORD_TOO_SHORT = 'PASSWORD_TOO_SHORT',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  AUTHENTICATION_REQUIRED = 'AUTHENTICATION_REQUIRED',
  ADMIN_PRIVILEGES_REQUIRED = 'ADMIN_PRIVILEGES_REQUIRED',
  AVATAR_NOT_FOUND = 'AVATAR_NOT_FOUND',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
}
