apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "default.fullname" . }}
  namespace: {{ include "default.namespace" . | quote }}
  labels:
    {{- include "default.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "default.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "default.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      serviceAccountName: {{ include "default.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-db
          image: {{ include "default.waitForDbImage" . | quote }}
          imagePullPolicy: {{ .Values.waitForDb.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            limits:
              cpu: {{ .Values.waitForDb.resources.limits.cpu | quote }}
              memory: {{ .Values.waitForDb.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.waitForDb.resources.requests.cpu | quote }}
              memory: {{ .Values.waitForDb.resources.requests.memory | quote }}
          command:
            - sh
            - -c
            - |
                echo "database host : {{ include "default.databaseHost" . }}"
                until nc -z {{ include "default.databaseHost" . }} 5432; do
                  echo "Waiting for PostgreSQL..."
                  sleep 2
                done
                echo "PostgreSQL is ready!"
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "default.image" . | quote }}
          imagePullPolicy: {{ include "default.imagePullPolicy" . }}
          command:
            - /usr/bin/dumb-init
            - --
            - sh
            - -c
            - |
                export DATABASE_URL="$(cat /etc/pleey/secrets/DATABASE_URL)"
                export JWT_SECRET="$(cat /etc/pleey/secrets/JWT_SECRET)"
                exec node --max-old-space-size=200 /usr/src/app/dist/src/app/main.js
          envFrom:
            - configMapRef:
                name: {{ include "default.fullname" . }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            {{- toYaml (omit .Values.startupProbe "enabled") | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- toYaml (omit .Values.livenessProbe "enabled") | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- toYaml (omit .Values.readinessProbe "enabled") | nindent 12 }}
          {{- end }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
          volumeMounts:
            - name: app-secrets
              mountPath: /etc/pleey/secrets
              readOnly: true
            - name: tmp
              mountPath: /tmp
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: app-secrets
          secret:
            secretName: {{ include "default.fullname" . }}
        - name: tmp
          emptyDir: {}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
