name: Shared - Continuous Integration

on:
  workflow_call:
    inputs:
      production-image-tag:
        description: Force the production backend/frontend image tag.
        required: false
        type: string
        default: ""
    outputs:
      built-prod-images:
        description: Production backend/frontend build metadata.
        value: ${{ jobs.build-prod.outputs.built-images }}

permissions: {}

jobs:
  linter:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/linter.yml@b553a696531fbd36743ccbb0c76c717971b8acdb # v0.35.4
    permissions:
      actions: read
      contents: read
      security-events: write
      statuses: write
    with:
      codeql-languages: "" # FIXME: Let default value when CodeQL will be available (paid feature)
      linter-env: |
        VALIDATE_TSX=false
        VALIDATE_GRAPHQL_PRETTIER=false
        VALIDATE_JSON_PRETTIER=false
        VALIDATE_JSX_PRETTIER=false
        VALIDATE_JAVASCRIPT_PRETTIER=false
        VALIDATE_TYPESCRIPT_PRETTIER=false
        VALIDATE_TYPESCRIPT_ES=false

  build:
    uses: hoverkraft-tech/ci-github-container/.github/workflows/docker-build-images.yml@260358ba1fd405c57bc669823d89c625971a3431 # v0.34.2
    permissions:
      contents: read
      packages: write
      issues: read
      pull-requests: read
      id-token: write
    with:
      oci-registry: ${{ vars.OCI_REGISTRY }}
      oci-registry-username: ${{ github.repository_owner }}
      sign: false
      images: |
        [
          {
            "name": "backend-ci",
            "context": ".",
            "dockerfile": "./application/backend/Dockerfile",
            "build-args": { "APP_PATH": "./application/backend/" },
            "target": "ci",
            "platforms": ["linux/amd64"]
          },
          {
            "name": "frontend-ci",
            "context": ".",
            "dockerfile": "./application/frontend/Dockerfile",
            "build-args": { "APP_PATH": "./application/frontend/" },
            "target": "ci",
            "platforms": ["linux/amd64"]
          }
        ]
    secrets:
      oci-registry-password: ${{ secrets.GITHUB_TOKEN }}

  continuous-integration:
    strategy:
      matrix:
        service: ["backend", "frontend"]
    uses: hoverkraft-tech/ci-github-nodejs/.github/workflows/continuous-integration.yml@6b74a8f070140f5c120f78026d58e4c00d1b1e37 # v0.24.2
    needs: build
    permissions:
      contents: read
      id-token: write
      pull-requests: write
      security-events: write
      packages: read
    with:
      working-directory: /usr/src/app
      container: |
        {
          "image": ${{ toJSON(fromJSON(needs.build.outputs.built-images)[format('{0}-ci', matrix.service)].images[0]) }},
          "credentials": {
            "username": ${{ toJson(github.repository_owner) }}
          },
          "pathMapping": {
            "/usr/src/app": ${{ toJson(format('./application/{0}', matrix.service)) }}
          }
        }
      code-ql: "" # FIXME: Set `typescript` when CodeQL will be available (paid feature)
      dependency-review: false # FIXME: Set `true` when Dependency Review will be available (paid feature)
    secrets:
      container-password: ${{ secrets.GITHUB_TOKEN }}

  build-prod:
    uses: hoverkraft-tech/ci-github-container/.github/workflows/docker-build-images.yml@260358ba1fd405c57bc669823d89c625971a3431 # v0.34.2
    needs: continuous-integration
    permissions:
      contents: read
      packages: write
      issues: read
      pull-requests: read
      id-token: write
    with:
      oci-registry: ${{ vars.OCI_REGISTRY }}
      oci-registry-username: ${{ github.repository_owner }}
      sign: false
      images: |
        [
          {
            "name": "backend",
            "tag": "${{ inputs.production-image-tag }}",
            "context": ".",
            "dockerfile": "./application/backend/Dockerfile",
            "build-args": { "APP_PATH": "./application/backend/" },
            "target": "prod",
            "platforms": ["linux/amd64"]
          },
          {
            "name": "frontend",
            "tag": "${{ inputs.production-image-tag }}",
            "context": ".",
            "dockerfile": "./application/frontend/Dockerfile",
            "build-args": { "APP_PATH": "./application/frontend/" },
            "target": "prod",
            "platforms": ["linux/amd64"]
          }
        ]
    secrets:
      oci-registry-password: ${{ secrets.GITHUB_TOKEN }}

  tests-charts:
    runs-on: ubuntu-latest
    needs: build-prod
    permissions:
      contents: read
      packages: read
    steps:
      - name: Test helm chart (umbrella)
        uses: hoverkraft-tech/ci-github-container/actions/helm/test-chart@260358ba1fd405c57bc669823d89c625971a3431 # v0.34.2
        with:
          helm-repositories: |
            cloudnative-pg https://cloudnative-pg.github.io/charts
            valkey https://valkey.io/valkey-helm/
          helm-set: |
            backend.image.registry=${{ fromJSON(needs.build-prod.outputs.built-images).backend.registry }}
            backend.image.repository=${{ fromJSON(needs.build-prod.outputs.built-images).backend.repository }}
            backend.image.tag=${{ fromJSON(needs.build-prod.outputs.built-images).backend.tags[0] }}
            backend.image.digest=${{ fromJSON(needs.build-prod.outputs.built-images).backend.digest }}
            backend.cloudnativepgOperator.enabled=true
            frontend.image.registry=${{ fromJSON(needs.build-prod.outputs.built-images).frontend.registry }}
            frontend.image.repository=${{ fromJSON(needs.build-prod.outputs.built-images).frontend.repository }}
            frontend.image.tag=${{ fromJSON(needs.build-prod.outputs.built-images).frontend.tags[0] }}
            frontend.image.digest=${{ fromJSON(needs.build-prod.outputs.built-images).frontend.digest }}
            global.imagePullSecrets[0].name=regcred
          oci-registry: ${{ vars.OCI_REGISTRY }}
          oci-registry-username: ${{ github.repository_owner }}
          oci-registry-password: ${{ github.token }}
