export const DEFAULT_PLAYABLE_CONTENT_IMPORT_MAX_FILE_SIZE_BYTES = 5 * 1024 * 1024;
export const PLAYABLE_CONTENT_IMPORT_MAX_FILE_SIZE_BYTES_TOKEN =
  'PLAYABLE_CONTENT_IMPORT_MAX_FILE_SIZE_BYTES_TOKEN';
